In [1]:
import pandas as pd
import numpy as np

In [44]:
data = pd.read_csv("/Users/meganpolak/Downloads/State_Combined_Df 3.csv")

In [62]:
data.head()

Year  FIPSStateCode  FIPSCountyCode  Income  IncRat     UPB   LTV  \
0  2017             72              15   60588  3.2928   71967  0.89   
1  2017             66              10  210264  4.0513  514837  0.94   
2  2017             66              10  114744  2.2109  425563  1.04   
3  2017             48             439  164988  2.3403  251800  0.75   
4  2017              6              99   56160  1.0537  290613  0.85   

   MortDate  Purpose  Product  Term  AmorTerm  NumBor  Occup    Rate  Amount  \
0      2016        2        1   180       180       2      1  0.0288   75000   
1      2016        2        1   360       360       2      1  0.0325  520000   
2      2016        1        1   360       360       2      1  0.0325  429831   
3      2016        2        1   360       360       2      1  0.0338  251800   
4      2016        2        1   360       360       2      1  0.0325  290613   

    Front    Back  BoCreditScor  
0  0.1118  0.2265             5  
1  0.1446  0.2370             5  
2  0.2312  0.3152             5  
3  0.1657  0.3430             4  
4  0.4062  0.4224             3

In [46]:
data.head()
data=data.drop('StateName',axis=1)
data=data.drop('Unnamed: 0',axis=1)

In [47]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390865 entries, 0 to 390864
Data columns (total 19 columns):
Year              390865 non-null int64
FIPSStateCode     390865 non-null int64
FIPSCountyCode    390865 non-null int64
Income            390865 non-null int64
IncRat            390865 non-null float64
UPB               390865 non-null int64
LTV               390865 non-null float64
MortDate          390865 non-null int64
Purpose           390865 non-null int64
Product           390865 non-null int64
Term              390865 non-null int64
AmorTerm          390865 non-null int64
NumBor            390865 non-null int64
Occup             390865 non-null int64
Rate              390865 non-null float64
Amount            390865 non-null int64
Front             390865 non-null float64
Back              390865 non-null float64
BoCreditScor      390865 non-null int64
dtypes: float64(5), int64(14)
memory usage: 56.7 MB
None


In [50]:
#segregate the data into separate variables so that the features and the labels are separated for faster computation
array = data.values
X = array[:,0:18]
Y = array[:,18]

In [51]:
# Import the necessary libraries 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [68]:
# implemnet Chi-Squared statistical test for non-negative features
#to select 4 of the best features from the dataset
#filter
# Feature extraction
test = SelectKBest(score_func=chi2, k=5)
fit = test.fit(X, Y)

# Summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)

features = fit.transform(X)
# Summarize selected features
print(features[0:18,:])

#Interpretation:
#You can see the scores for each attribute and the 5 attributes chosen 
#(those with the highest scores ( variance)): year, MortDate,IncRat,Amount,Back, may contain more useful information 
#. This scores will help you further in determining the best features for training your model.
#P.S.: The first row denotes the names of the features. For preprocessing of the dataset, the names have been numerically encoded.

[4.492e+00 2.569e+02 1.287e+04 3.662e+08 4.846e+03 2.967e+08 1.089e+03
 4.553e+00 1.031e+03 3.577e-27 1.706e+05 1.706e+05 1.284e+03 1.587e+01
 8.026e+00 2.971e+08 6.894e+04 1.100e+05]
[[6.059e+04 7.197e+04 1.800e+02 1.800e+02 7.500e+04]
 [2.103e+05 5.148e+05 3.600e+02 3.600e+02 5.200e+05]
 [1.147e+05 4.256e+05 3.600e+02 3.600e+02 4.298e+05]
 [1.650e+05 2.518e+05 3.600e+02 3.600e+02 2.518e+05]
 [5.616e+04 2.906e+05 3.600e+02 3.600e+02 2.906e+05]
 [1.158e+05 1.030e+05 3.600e+02 3.600e+02 1.030e+05]
 [9.455e+04 1.900e+05 3.600e+02 3.600e+02 1.900e+05]
 [2.216e+05 3.810e+05 3.600e+02 3.600e+02 3.810e+05]
 [1.136e+05 2.330e+05 3.600e+02 3.600e+02 2.330e+05]
 [6.800e+04 2.566e+05 3.600e+02 3.600e+02 2.576e+05]
 [1.149e+05 2.115e+05 3.600e+02 3.600e+02 2.115e+05]
 [8.782e+04 2.220e+05 3.600e+02 3.600e+02 2.220e+05]
 [4.313e+04 1.420e+05 3.600e+02 3.600e+02 1.420e+05]
 [8.168e+04 2.549e+05 3.600e+02 3.600e+02 2.549e+05]
 [6.928e+04 1.732e+05 3.600e+02 3.600e+02 1.732e+05]
 [9.006e+04 1.650e+05

In [69]:
data.columns

Index(['Year', 'FIPSStateCode', 'FIPSCountyCode', 'Income', 'IncRat', 'UPB',
       'LTV', 'MortDate', 'Purpose', 'Product', 'Term', 'AmorTerm', 'NumBor',
       'Occup', 'Rate', 'Amount', 'Front', 'Back', 'BoCreditScor'],
      dtype='object')

In [70]:
#implement Recursive Feature Elimination which is a type of wrapper feature selection method.
#In this case logistic regression to select top 5 features 
# Wrapper
# Import your necessary dependencies
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [71]:
# Feature extraction we select 5 
model = LogisticRegression()
rfe = RFE(model, 5)
fit = rfe.fit(X, Y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

Num Features: 5
Selected Features: [False False False False  True False  True False  True False False False
 False False False False  True  True]
Feature Ranking: [ 4  5  8  9  1 10  1  3  1 14  6  7  2 12 13 11  1  1]


In [72]:
# top 5 features :'IncRat','LTV','Purpose', 'Back', 'BoCreditScor'

data.columns

Index(['Year', 'FIPSStateCode', 'FIPSCountyCode', 'Income', 'IncRat', 'UPB',
       'LTV', 'MortDate', 'Purpose', 'Product', 'Term', 'AmorTerm', 'NumBor',
       'Occup', 'Rate', 'Amount', 'Front', 'Back', 'BoCreditScor'],
      dtype='object')

In [73]:
#Next use Ridge regression which is basically a regularization technique 
#and an embedded feature selection techniques as well.

from sklearn.linear_model import Ridge

In [74]:
#use Ridge regression to determine the coefficient R2.
ridge = Ridge(alpha=1.0)
ridge.fit(X,Y)

/Users/meganpolak/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number8.438565e-17
  overwrite_a=True).T


Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [75]:
# A helper method for printing the coefficients.Spot all the coefficient terms appended with 
#the feature variables. 
#It will again help to choose the most essential features.

def pretty_print_coefs(coefs, names = None, sort = False):
    if names == None:
        names = ["X%s" % x for x in range(len(coefs))]
    lst = zip(coefs, names)
    if sort:
        lst = sorted(lst,  key = lambda x:-np.abs(x[0]))
    return " + ".join("%s * %s" % (round(coef, 4), name)
                                   for coef, name in lst)

In [76]:
#pass Ridge model's coefficient terms also known as L2-Regularization.
#For correlated features, it means that they tend to get similar coefficients.
#Feature having negative coefficients don't contribute that much. 

print ("Ridge model:", pretty_print_coefs(ridge.coef_))

Ridge model: 0.0028 * X0 + 0.0012 * X1 + -0.0001 * X2 + -0.0 * X3 + 0.0194 * X4 + -0.0 * X5 + -1.1392 * X6 + -0.0226 * X7 + -0.0402 * X8 + 0.0 * X9 + 0.05 * X10 + -0.05 * X11 + 0.1501 * X12 + 0.1536 * X13 + -19.4685 * X14 + 0.0 * X15 + 0.0 * X16 + -0.0001 * X17


In [81]:
data.corr()



Year  FIPSStateCode  FIPSCountyCode    Income    IncRat  \
Year            1.000000      -0.021517       -0.025636  0.036659  0.008628   
FIPSStateCode  -0.021517       1.000000       -0.013937  0.001478  0.009610   
FIPSCountyCode -0.025636      -0.013937        1.000000 -0.027830 -0.003666   
Income          0.036659       0.001478       -0.027830  1.000000  0.979218   
IncRat          0.008628       0.009610       -0.003666  0.979218  1.000000   
UPB             0.231458      -0.091363       -0.113254  0.350384  0.284367   
LTV             0.107277       0.040260        0.044037 -0.090501 -0.081110   
MortDate        0.994804      -0.022564       -0.022296  0.036547  0.009106   
Purpose        -0.232827      -0.048312       -0.011448  0.046283  0.050517   
Product              NaN            NaN             NaN       NaN       NaN   
Term            0.242282      -0.003498       -0.040408 -0.059783 -0.084580   
AmorTerm        0.242282      -0.003498       -0.040408 -0.059783 -0.084580   
NumBor         -0.076657      -0.000215        0.009549  0.164347  0.172112   
Occup           0.001220      -0.005460       -0.031827  0.130111  0.150097   
Rate           -0.270452       0.006327       -0.017086 -0.078948 -0.082245   
Amount          0.231811      -0.091283       -0.113440  0.350492  0.284438   
Front          -0.030585      -0.005452       -0.005066 -0.016973 -0.017157   
Back           -0.029309      -0.005688       -0.004196 -0.016044 -0.016179   
BoCreditScor   -0.026387       0.000621       -0.021174  0.074443  0.070618   

                     UPB       LTV  MortDate   Purpose  Product      Term  \
Year            0.231458  0.107277  0.994804 -0.232827      NaN  0.242282   
FIPSStateCode  -0.091363  0.040260 -0.022564 -0.048312      NaN -0.003498   
FIPSCountyCode -0.113254  0.044037 -0.022296 -0.011448      NaN -0.040408   
Income          0.350384 -0.090501  0.036547  0.046283      NaN -0.059783   
IncRat          0.284367 -0.081110  0.009106  0.050517      NaN -0.084580   
UPB             1.000000  0.053096  0.229651  0.005786      NaN  0.219731   
LTV             0.053096  1.000000  0.107165 -0.418945      NaN  0.371189   
MortDate        0.229651  0.107165  1.000000 -0.234117      NaN  0.241180   
Purpose         0.005786 -0.418945 -0.234117  1.000000      NaN -0.343961   
Product              NaN       NaN       NaN       NaN      NaN       NaN   
Term            0.219731  0.371189  0.241180 -0.343961      NaN  1.000000   
AmorTerm        0.219731  0.371189  0.241180 -0.343961      NaN  1.000000   
NumBor          0.148523 -0.112360 -0.075462  0.128165      NaN -0.126502   
Occup           0.028125 -0.028245  0.001982 -0.052613      NaN -0.001985   
Rate            0.002920  0.208441 -0.274661 -0.191750      NaN  0.470174   
Amount          0.999808  0.053120  0.229615  0.005737      NaN  0.219200   
Front           0.013150  0.026065 -0.030181  0.015496      NaN  0.013096   
Back            0.011897  0.025522 -0.028907  0.014698      NaN  0.012645   
BoCreditScor    0.083572 -0.254027 -0.026367  0.117523      NaN -0.135790   

                AmorTerm    NumBor     Occup      Rate    Amount     Front  \
Year            0.242282 -0.076657  0.001220 -0.270452  0.231811 -0.030585   
FIPSStateCode  -0.003498 -0.000215 -0.005460  0.006327 -0.091283 -0.005452   
FIPSCountyCode -0.040408  0.009549 -0.031827 -0.017086 -0.113440 -0.005066   
Income         -0.059783  0.164347  0.130111 -0.078948  0.350492 -0.016973   
IncRat         -0.084580  0.172112  0.150097 -0.082245  0.284438 -0.017157   
UPB             0.219731  0.148523  0.028125  0.002920  0.999808  0.013150   
LTV             0.371189 -0.112360 -0.028245  0.208441  0.053120  0.026065   
MortDate        0.241180 -0.075462  0.001982 -0.274661  0.229615 -0.030181   
Purpose        -0.343961  0.128165 -0.052613 -0.191750  0.005737  0.015496   
Product              NaN       NaN       NaN       NaN       NaN       NaN   
Term            1.000000 -0.126502 -0.00